name: JExVote
version: '3.2.5'
main: de.jexcellence.vote.JExVoteFree
description: All-in-one vote listener, reward & leaderboard system (Free Edition)
api-version: '1.21'
author: JExcellence
website: https://jexcellence.de
folia-supported: true

softdepend:
  - JExEconomy
  - Vault
  - PlaceholderAPI
