name: JExVote
version: '3.0.0'
main: de.jexcellence.vote.JExVotePremium
description: All-in-one vote listener, reward & leaderboard system (Premium Edition)
api-version: '1.21'
author: JExcellence
website: https://jexcellence.de
loader: de.jexcellence.dependency.loader.PaperPluginLoader
folia-supported: true
dependencies:
  server:
    JExEconomy:
      load: BEFORE
      required: false
      join-classpath: true
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
