name: JExVote
version: '3.1.0'
main: de.jexcellence.vote.JExVotePremium
description: All-in-one vote listener, reward & leaderboard system (Premium Edition)
api-version: '1.21'
author: JExcellence
website: https://jexcellence.de
folia-supported: true

softdepend:
  - JExEconomy
  - Vault
  - PlaceholderAPI
